training_pipeline_config:
  pipeline_name: fraud_detection_artifact
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://drive.google.com/uc?export=download&confirm=6gh6&id=1VNpyNkGxHdskfdTNRSjjyNa5qC9u0JyV
  dataset_local_location: C:\Users\Aditya\OneDrive\Documents\DataScience\SA\projects\fraud-transaction-detection\Fraud.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html
  
